/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 26-Jan-2020 13:57:49
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 51
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /Applications/MATLAB_R2018a.app/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int BL = 51;
const real32_T B[51] = {
    0.00756539451, -0.01149180066,-0.004271964077,0.0003535575815, 0.003802435007,
   0.006187047344, 0.006911808625, 0.005282577127, 0.001192335272,-0.004611292854,
   -0.01044458337, -0.01406532526, -0.01344149839,-0.007485062815, 0.003263459308,
    0.01636486501,   0.0277939178,   0.0328727141,  0.02743673138, 0.009163923562,
   -0.02150698006, -0.06104771048,  -0.1033860892,  -0.1411015838,  -0.1671450883,
     0.8235622644,  -0.1671450883,  -0.1411015838,  -0.1033860892, -0.06104771048,
   -0.02150698006, 0.009163923562,  0.02743673138,   0.0328727141,   0.0277939178,
    0.01636486501, 0.003263459308,-0.007485062815, -0.01344149839, -0.01406532526,
   -0.01044458337,-0.004611292854, 0.001192335272, 0.005282577127, 0.006911808625,
   0.006187047344, 0.003802435007,0.0003535575815,-0.004271964077, -0.01149180066,
    0.00756539451
};
